### ISSUE TITLE
README RE-REMASTERED

### ISSUE THREAD

**Issue by Luigi38** [Luigi38/ProjectNextop#20]
**HTMLTML 문서처럼** Front-README 만들고
목차처럼 만든 뒤 서브 폴더에 README 만들고

Front 목차에 링크 넣어두면 될 듯 합니다.

**Comment by Luigi38** [comment]
+ Baekjoon 폴더 RE-REMASTERED

**Comment by Luigi38** [comment]
Footprints도 따로 h1으로 해서 만드는 것도 나음.

**Comment by MineEric64** [comment]
쌤한테 말할 것: 컴퓨터를 서버처럼 사용해서 컴퓨터 파일들을
핸드폰에서 원격으로 접속할 수 있는 방법은 있는가?

**Comment by Luigi38** [comment]
README RE-REMASTERED 끝남
이제 더 이상 개선할 수 있는 부분은 지금까지는 없다.
