### ISSUE TITLE
OP.GG 면접

### ISSUE THREAD

**Issue by Luigi38** [Luigi38/ProjectNextop#4]
1. rest api (특징, 구성, 정의, 장단점)
2. 서버 & 클라이언트 분리
3. 백엔드란 무엇인가 (최대한 많이)
4. 프레임워크
5. 그래프QL (No SQL) 정의, 특징, 장단점
6. DB
5. 프로젝트 한거 정리 (장단점, 특징)

**Comment by MineEric64** [comment]
1시간 전...

**Comment by MineEric64** [comment]
1. 간단한 자기소개 [ 자신이 했던 프로젝트 위주 ]
2. 지원한 동기
3. 코딩 테스트

그 후 오버워치를 하......지는 못했고 기말고사가 1주일도 안남아서 공부했음 ㅋ

![TQ](https://raw.githubusercontent.com/Luigi38/ProjectNextop/main/Resources/TQ.png)
